apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: vernemq
  name: vernemq
  namespace: messaging
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      vernemq: k8s
